server:
  port: 8080

management:
  port: 8081

endpoints:
  health:
    enabled: true
  jmx:
    enabled: true
  metrics:
    enabled: false

db:
  host: localhost
  port: 5432
  name: postgres
  user: postgres
  password: password
